/**
 * Public car parks in central Bucharest. Generated -- do not edit by hand.
 *
 *     node scripts/fetch-parking.mjs
 *
 * 83 car parks (32 structures, 23 with a recorded
 * capacity), fetched 2026-08-07.
 *
 * WHAT THESE ARE. Places the map knows exist, at roughly the size recorded.
 * Nothing here says whether there is space in one now -- OSM has no such field,
 * no Bucharest authority publishes one, and guessing would make the app's
 * central promise worthless. They carry no observation and read as "Fără
 * raportări" until a driver files one, at which point they join the belief model
 * like any other public kerb.
 *
 * WHY NOT THE CITY'S OWN DATA. There is none to have. Compania Municipală
 * Parking București runs the blue zone and publishes no API; the PMB planning
 * portal has no documented REST endpoint; data.gov.ro carries no Bucharest
 * parking dataset; and residents' parking is administered by each sector
 * separately. When any of that changes, this file gains a sibling rather than a
 * rewrite -- `source` already distinguishes `osm` from `city`.
 *
 * Unlike `SEED_SPOTS` in lib/api.ts, this is not stand-in data and
 * `lib/remote.ts` must not suppress it. The seeds are invented and a configured
 * backend rightly replaces them; these are real places.
 *
 * Data (c) OpenStreetMap contributors, available under the Open Database
 * Licence. Any screen that draws this layer has to say so.
 */

import type { ParkingSpot } from "@/types";

/** The area this file covers, as [south, west, north, east]. */
export const PARKING_AREA = [44.38, 26.02, 44.5, 26.18] as const;

/** When the layer was last pulled from OpenStreetMap. */
export const PARKING_FETCHED_AT = "2026-08-07T12:59:36.035Z";

/** Required wherever the layer is drawn. */
export const PARKING_ATTRIBUTION = "© OpenStreetMap contributors (ODbL)";

/**
 * Car parks with `updatedAt` left at the fetch time.
 *
 * That timestamp is when the *record* was read, not when anybody looked at the
 * car park, and nothing may read it as an observation. `reportsFor` in
 * lib/spot-belief.ts skips the seed claim for these precisely so it cannot.
 */
export const PUBLIC_PARKING: ParkingSpot[] = [
  {
    id: "osm_n1306581986",
    title: "Fabrica de Pâine",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.453833,
    longitude: 26.123458,
    area: "Sector 2 · Piața Obor",
    totalCount: 20,
    paid: false,
  },
  {
    id: "osm_n1927117383",
    title: "B-dul 1 Decembrie 1918",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.430047,
    longitude: 26.173766,
    area: "Sector 3 · Malaxa - Faur",
    totalCount: 30,
  },
  {
    id: "osm_n2405137558",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.389291,
    longitude: 26.111021,
    area: "Sector 4 · Berceni",
    totalCount: 15,
  },
  {
    id: "osm_n2497264135",
    title: "Muzeul Satului",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.470545,
    longitude: 26.077225,
    area: "Sector 1 · Domenii",
  },
  {
    id: "osm_n2866066043",
    title: "Parcare Bloc A5, Sc. B-C",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.482003,
    longitude: 26.050067,
    area: "Sector 1 · Pajura",
    totalCount: 5,
    paid: false,
  },
  {
    id: "osm_n3789863358",
    title: "Parcare Kaufland Pantelimon",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.44224,
    longitude: 26.15328,
    area: "Sector 2 · Delfinului",
    paid: false,
  },
  {
    id: "osm_n4090219208",
    title: "Parcare Subterana",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.380884,
    longitude: 26.138142,
    area: "Sector 4 · Apărătorii Patriei",
  },
  {
    id: "osm_n458746312",
    title: "Parcare Sala Polivalenta",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.405784,
    longitude: 26.109477,
    area: "Sector 4 · Tineretului",
  },
  {
    id: "osm_n458746341",
    title: "Parcare Sala Polivalenta 2",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.404979,
    longitude: 26.110948,
    area: "Sector 4 · Văcărești",
  },
  {
    id: "osm_n4621661072",
    title: "Parcare Promenada Mall",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.478383,
    longitude: 26.103352,
    area: "Sector 1 · Aviației",
    paid: true,
  },
  {
    id: "osm_n567247284",
    title: "Parcare complex",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.482872,
    longitude: 26.051634,
    area: "Sector 1 · Pajura",
  },
  {
    id: "osm_n5868976736",
    title: "Parcare Ibis Styles",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.483854,
    longitude: 26.097031,
    area: "Sector 1 · Aviației",
  },
  {
    id: "osm_n587668981",
    title: "Parcare Sala Polivalenta 2",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.40442,
    longitude: 26.110221,
    area: "Sector 4 · Văcărești",
  },
  {
    id: "osm_n6272992239",
    title: "Parcare rezidențială",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.391409,
    longitude: 26.109004,
    area: "Sector 4 · Berceni",
  },
  {
    id: "osm_n6272992240",
    title: "Parcare rezidențială",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.390975,
    longitude: 26.109114,
    area: "Sector 4 · Berceni",
  },
  {
    id: "osm_n6952582144",
    title: "Parcare vis-a-vis de Piața Progresul",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.392037,
    longitude: 26.093245,
    area: "Sector 4 · Giurgiului",
  },
  {
    id: "osm_n6960232997",
    title: "Parcare Mega Image",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.401957,
    longitude: 26.062538,
    area: "Sector 5 · Rahova",
  },
  {
    id: "osm_n6974620555",
    title: "Parcare Mega Image",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.476586,
    longitude: 26.093411,
    area: "Sector 1 · Aviației",
    totalCount: 10,
  },
  {
    id: "osm_n6974681272",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.476365,
    longitude: 26.093073,
    area: "Sector 1 · Aviației",
    totalCount: 8,
  },
  {
    id: "osm_n7124470376",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.390895,
    longitude: 26.085894,
    area: "Sector 5 · Giurgiului",
  },
  {
    id: "osm_n7124470380",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.391069,
    longitude: 26.085612,
    area: "Sector 5 · Giurgiului",
  },
  {
    id: "osm_n7124581196",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.391382,
    longitude: 26.085636,
    area: "Sector 5 · Giurgiului",
    totalCount: 8,
  },
  {
    id: "osm_w1054204433",
    title: "Parcare subterană",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.42966,
    longitude: 26.134797,
    area: "Sector 3 · Decebal",
    totalCount: 718,
    pricePerHour: 5,
    paid: true,
  },
  {
    id: "osm_w1154778693",
    title: "Parcare vizitatori",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.442228,
    longitude: 26.159577,
    area: "Sector 2 · Delfinului",
  },
  {
    id: "osm_w1155808869",
    title: "Piața Gemeni",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.445143,
    longitude: 26.111193,
    area: "Sector 2 · Piața Gemeni",
    paid: false,
  },
  {
    id: "osm_w1194682792",
    title: "Nicolae Caranfil",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.485612,
    longitude: 26.091945,
    area: "Sector 1 · Aviației",
    paid: true,
  },
  {
    id: "osm_w1201025711",
    title: "Parcare, Strada George Constantinescu",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.479371,
    longitude: 26.11693,
    area: "Sector 2 · Platforma Pipera",
    totalCount: 147,
    paid: true,
  },
  {
    id: "osm_w1257787974",
    title: "Parcare vizitatori",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.428184,
    longitude: 26.032364,
    area: "Sector 6 · Drumul Taberei",
  },
  {
    id: "osm_w129316969",
    title: "Parcarea Piața Universității",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.434976,
    longitude: 26.100897,
    area: "Sector 3 · Colțea",
    totalCount: 425,
    paid: true,
  },
  {
    id: "osm_w1306282790",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.415133,
    longitude: 26.138922,
    area: "Sector 3 · Dristor",
  },
  {
    id: "osm_w1334758791",
    title: "Dizabilități",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.490058,
    longitude: 26.179524,
    totalCount: 2,
  },
  {
    id: "osm_w1527302829",
    title: "Parcare E",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.479095,
    longitude: 26.067607,
    area: "Sector 1 · Piața Presei",
    totalCount: 175,
    paid: true,
  },
  {
    id: "osm_w1534275559",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.431898,
    longitude: 26.027734,
    area: "Sector 6 · Militari",
  },
  {
    id: "osm_w184169515",
    title: "Parcare Unirea",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.428573,
    longitude: 26.105445,
    area: "Sector 3 · Sf. Vineri",
    totalCount: 350,
  },
  {
    id: "osm_w197738034",
    title: "Parcare cu plată",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.427857,
    longitude: 26.0999,
    area: "Sector 4 · Calicilor",
    paid: true,
  },
  {
    id: "osm_w198218844",
    title: "CAT 2475",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.459475,
    longitude: 26.138648,
    area: "Sector 2 · Doamna Ghica",
  },
  {
    id: "osm_w201015355",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.415056,
    longitude: 26.161644,
    area: "Sector 3 · Sălăjan",
  },
  {
    id: "osm_w202691013",
    title: "Parcare D1",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.476326,
    longitude: 26.061822,
    area: "Sector 1 · Domenii",
    totalCount: 250,
    paid: true,
  },
  {
    id: "osm_w202691019",
    title: "Parcare D2",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.477647,
    longitude: 26.061307,
    area: "Sector 1 · Piața Presei",
    totalCount: 250,
    paid: true,
  },
  {
    id: "osm_w202691391",
    title: "Parcare C",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.474789,
    longitude: 26.06295,
    area: "Sector 1 · Domenii",
    totalCount: 500,
    paid: true,
  },
  {
    id: "osm_w202693019",
    title: "Parcare B2",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.476226,
    longitude: 26.068086,
    area: "Sector 1 · Piața Presei",
    totalCount: 250,
    paid: true,
  },
  {
    id: "osm_w202693022",
    title: "Parcare B1",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.475498,
    longitude: 26.067722,
    area: "Sector 1 · Piața Presei",
    totalCount: 300,
    paid: true,
  },
  {
    id: "osm_w206980595",
    title: "Parcare Piața Obor",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.450442,
    longitude: 26.128659,
    area: "Sector 2 · Obor",
    paid: true,
  },
  {
    id: "osm_w215352124",
    title: "Parcare privata",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.388992,
    longitude: 26.117029,
    area: "Sector 4 · Berceni",
  },
  {
    id: "osm_w215353420",
    title: "Parcare Leroy Merlin",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.397232,
    longitude: 26.123535,
    area: "Sector 4 · Piața Sudului",
  },
  {
    id: "osm_w219710325",
    title: "Piața Constituției",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.427299,
    longitude: 26.091696,
    area: "Sector 5 · Antim",
    paid: true,
  },
  {
    id: "osm_w220084862",
    title: "Parcare Ramada Hotel & Suites Bucharest North",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.486347,
    longitude: 26.089714,
    area: "Sector 1 · Herăstrău",
  },
  {
    id: "osm_w225503238",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.416248,
    longitude: 26.049686,
    area: "Sector 6 · Tudor Vladimirescu",
  },
  {
    id: "osm_w225503246",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.416293,
    longitude: 26.049905,
    area: "Sector 6 · Tudor Vladimirescu",
  },
  {
    id: "osm_w225503247",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.416126,
    longitude: 26.049719,
    area: "Sector 6 · Tudor Vladimirescu",
  },
  {
    id: "osm_w225505482",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.419019,
    longitude: 26.042458,
    area: "Sector 6 · Tudor Vladimirescu",
  },
  {
    id: "osm_w226044616",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.42157,
    longitude: 26.127909,
    area: "Sector 3 · Dudeşti",
    paid: true,
  },
  {
    id: "osm_w239206890",
    title: "Parcare Piața Revoluției",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.438258,
    longitude: 26.097887,
    area: "Sector 1 · Teatrului",
    paid: true,
  },
  {
    id: "osm_w239335338",
    title: "Parcare Subterană Piața Obor",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.450053,
    longitude: 26.130085,
    area: "Sector 2 · Obor",
    paid: true,
  },
  {
    id: "osm_w245153561",
    title: "Parcare SUUB",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.437218,
    longitude: 26.070935,
    area: "Sector 5 · Cotroceni",
    paid: false,
  },
  {
    id: "osm_w289369482",
    title: "Parcare IDM",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.449444,
    longitude: 26.065565,
    area: "Sector 1 · Belvedere",
  },
  {
    id: "osm_w294717388",
    title: "Parcare Citygo",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.43275,
    longitude: 26.126118,
    area: "Sector 2 · Delea veche",
    paid: true,
  },
  {
    id: "osm_w339179191",
    title: "Parcare Mega Image",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.420212,
    longitude: 26.141225,
    area: "Sector 3 · Dristor",
  },
  {
    id: "osm_w389242430",
    title: "Parcare, Calea Moșilor",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.436481,
    longitude: 26.110788,
    area: "Sector 2 · Mântuleasa",
    totalCount: 20,
    paid: false,
  },
  {
    id: "osm_w395019633",
    title: "Parcare Lidl",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.491369,
    longitude: 26.032863,
    area: "Sector 1 · Bazilescu",
  },
  {
    id: "osm_w405063050",
    title: "Parcare Lidl",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.410305,
    longitude: 26.123752,
    area: "Sector 3 · Vitan",
    paid: false,
  },
  {
    id: "osm_w41337309",
    title: "Parcare Buzești 57",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.449897,
    longitude: 26.082826,
    area: "Sector 1 · Buzești",
    pricePerHour: 40,
    paid: true,
  },
  {
    id: "osm_w414258561",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.441043,
    longitude: 26.153803,
    area: "Sector 2 · Delfinului",
  },
  {
    id: "osm_w426665177",
    title: "Parcare Mega Image",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.437503,
    longitude: 26.168744,
    area: "Sector 2 · Pantelimon",
    paid: false,
  },
  {
    id: "osm_w43112614",
    title: "Parcare Sala Polivalenta",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.405796,
    longitude: 26.111325,
    area: "Sector 4 · Văcărești",
    paid: false,
  },
  {
    id: "osm_w494656610",
    title: "Parcare Centrul Comercial Huedin",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.383949,
    longitude: 26.102129,
    area: "Sector 4 · Giurgiului",
  },
  {
    id: "osm_w53178743",
    title: "Parcarea Penitenciarul Rahova",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.394714,
    longitude: 26.032551,
    area: "Sector 5 · Odăi",
    paid: true,
  },
  {
    id: "osm_w572777932",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.388412,
    longitude: 26.106189,
    area: "Sector 4 · Berceni",
  },
  {
    id: "osm_w585021140",
    title: "Pridvorului",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.407861,
    longitude: 26.113038,
    area: "Sector 4 · Tineretului",
    paid: true,
  },
  {
    id: "osm_w603740402",
    title: "Parcare sosea",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.443275,
    longitude: 26.154644,
    area: "Sector 2 · Delfinului",
    paid: true,
  },
  {
    id: "osm_w621211529",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.450622,
    longitude: 26.069779,
    area: "Sector 1 · Gara de Nord",
  },
  {
    id: "osm_w623081850",
    title: "Parcare National Arena",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.435027,
    longitude: 26.153952,
    area: "Sector 2 · Vatra Luminoasă",
    paid: true,
  },
  {
    id: "osm_w658281398",
    title: "Parcare Cocor",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.43024,
    longitude: 26.10462,
    area: "Sector 3 · Decebal",
  },
  {
    id: "osm_w675017438",
    title: "Parking Lot of Bl. 3",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.392209,
    longitude: 26.102205,
    area: "Sector 4 · Giurgiului",
    totalCount: 10,
    paid: true,
  },
  {
    id: "osm_w675021381",
    title: "Parking Lot Bl. 2",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.392169,
    longitude: 26.10214,
    area: "Sector 4 · Giurgiului",
    totalCount: 10,
    paid: true,
  },
  {
    id: "osm_w69562800",
    title: "Parcare Piața Operei",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.434419,
    longitude: 26.078394,
    area: "Sector 5 · Berzei",
    totalCount: 80,
    paid: true,
  },
  {
    id: "osm_w735407075",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.392515,
    longitude: 26.123317,
    area: "Sector 4 · Piața Sudului",
    totalCount: 300,
  },
  {
    id: "osm_w762323740",
    title: "Parcare cu plată",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.490089,
    longitude: 26.091179,
    area: "Sector 1 · Aviației",
    paid: true,
  },
  {
    id: "osm_w769890159",
    title: "Parcare Lidl",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.416503,
    longitude: 26.139888,
    area: "Sector 3 · Dristor",
    paid: false,
  },
  {
    id: "osm_w837076382",
    title: "Parcare supraetajată",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.38626,
    longitude: 26.130454,
    area: "Sector 4 · Berceni",
  },
  {
    id: "osm_w858843383",
    title: "Parcare subterană",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.412976,
    longitude: 26.039027,
    area: "Sector 6 · Tudor Vladimirescu",
  },
  {
    id: "osm_w941432422",
    title: "Parcare",
    access: "public",
    source: "osm",
    kind: "street",
    status: "taken",
    latitude: 44.492913,
    longitude: 26.092811,
    area: "Sector 1 · Băneasa",
  },
  {
    id: "osm_w95854777",
    title: "Parcare, Șoseaua Olteniței",
    access: "public",
    source: "osm",
    kind: "garage",
    status: "taken",
    latitude: 44.401032,
    longitude: 26.099536,
    area: "Sector 4 · Bellu - Eroii Revoluției",
  },
].map((spot) => ({ ...spot, updatedAt: PARKING_FETCHED_AT }) as ParkingSpot);
