-- Availability windows: the park-sharing half of the app.
--
-- A window is a stretch of time an owner is offering their own space, free or
-- for a price. It is a different species of fact from a status report and the
-- table shows it: no reporter, because an owner is not one; no confidence,
-- because there is nothing to be unsure about; and not append-only, because an
-- owner changing their plans edits the offer rather than filing a correction
-- that argues with their earlier self.
--
-- THE ONE RULE THAT IS NOT NEGOTIABLE. A window may only ever hang off a
-- `private` spot whose `owner_id` is the caller.
--
-- Lending or letting a parking place you own is lawful in Romania: it is
-- property (Cod Civil; Legea 196/2018 where the space sits inside a residents'
-- association, whose own rules may still forbid subletting a commonly-held
-- one). Doing the same with a public kerb is not -- "reserving" or handing on a
-- space on the public road is a contravention of 500-2.500 lei, and obstructing
-- a public road reaches art. 339 Cod Penal. It is the rock MonkeyParking ran
-- onto in San Francisco.
--
-- So the constraint below is not a product decision a later feature may relax
-- for convenience. It is the line between a listing and an offence, which is
-- why it is a trigger and not a policy: a policy is skipped by `service_role`.

create table if not exists public.availability_windows (
  -- Text, and generated by the client, because the app builds the window
  -- object before it is offered and the same id has to identify it on screen
  -- and in the row. See `toWindowInsert` in lib/supabase-rows.ts.
  id text primary key,
  spot_id text not null references public.spots (id) on delete cascade,

  -- Minutes from local midnight in Bucharest, e.g. 540 for 09:00. Not a
  -- `time`, and not a `timestamptz`: this is a wall clock, not an instant. See
  -- lib/bucharest-time.ts for why the distinction survives into the app.
  --
  -- `to_minute` may be <= `from_minute`, which means the window runs past
  -- midnight. That is why there is no `to_minute > from_minute` check: an
  -- overnight offer is the ordinary case for a residential garage.
  from_minute integer not null check (from_minute >= 0 and from_minute < 1440),
  to_minute integer not null check (to_minute >= 0 and to_minute < 1440),

  -- Weekdays it repeats on, 0 = Sunday. Null means every day.
  days smallint[] check (
    days is null
    or (
      array_length(days, 1) between 1 and 7
      and days <@ array[0, 1, 2, 3, 4, 5, 6]::smallint[]
    )
  ),

  starts_on date,
  ends_on date,

  -- Absent means the owner is lending it for free, which is a real and
  -- different answer from zero lei an hour.
  price_per_hour numeric(6, 2) check (price_per_hour >= 0),

  -- Gate code, which bay, how to get in.
  note text,

  -- Denormalised from `spots` so row level security can check it without a
  -- join on every statement. Kept honest by the trigger below.
  owner_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),

  constraint availability_windows_dates_ordered check (
    starts_on is null or ends_on is null or ends_on >= starts_on
  )
);

create index if not exists availability_windows_spot_idx
  on public.availability_windows (spot_id);
create index if not exists availability_windows_owner_idx
  on public.availability_windows (owner_id);

comment on table public.availability_windows is
  'An owner offering their own private space for a stretch of wall-clock time.';

-- ---------------------------------------------------------------------------
-- Only your own private spot may be offered
-- ---------------------------------------------------------------------------

create or replace function public.refuse_windows_on_spots_you_do_not_own()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  spot record;
begin
  select access, owner_id into spot from public.spots where id = new.spot_id;

  if spot is null then
    raise exception 'No such spot: %', new.spot_id
      using errcode = 'foreign_key_violation';
  end if;

  -- Offering a stretch of public road is an offence, not a feature.
  if spot.access <> 'private' then
    raise exception 'A public space cannot be offered: it is not yours to give'
      using errcode = 'insufficient_privilege';
  end if;

  if spot.owner_id is distinct from new.owner_id then
    raise exception 'Only the owner of a spot may offer it'
      using errcode = 'insufficient_privilege';
  end if;

  return new;
end;
$$;

create trigger availability_windows_owner_only
  before insert or update on public.availability_windows
  for each row execute function public.refuse_windows_on_spots_you_do_not_own();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.availability_windows enable row level security;

-- Read by everybody, which is the point: a listing nobody can see helps
-- nobody. Only writing is restricted.
create policy "Offers are readable by everybody"
  on public.availability_windows for select
  to anon, authenticated
  using (true);

create policy "An owner offers their own spot"
  on public.availability_windows for insert
  to authenticated
  with check (owner_id = (select auth.uid()));

create policy "An owner changes their own offer"
  on public.availability_windows for update
  to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

-- Scoped rather than refused: a request for somebody else's window deletes
-- nothing instead of erroring, which is what lets
-- `deleteAvailabilityWindow` stay a one-liner with no owner check of its own.
create policy "An owner withdraws their own offer"
  on public.availability_windows for delete
  to authenticated
  using (owner_id = (select auth.uid()));

grant select on public.availability_windows to anon, authenticated;
grant insert, update, delete on public.availability_windows to authenticated;
